addpath('3rd-party', 'sample-maps', 'tests', 'tools')
mapMakerGUI;

% START Welcome Message
fontName = 'FixedWidth';
fontSize = 12;

msg_body = [ ...
    'Welcome to the EKF SLAM MATLAB Simulator!' ...
    char(10) char(10) ...
    'To get started, either load one of the pre-made maps located in' ...
    char(10) ...
    'the root folder or build your own using waypoints, landmarks and' ...
    char(10) ...
    'obstacles.' ...
    ];

msg_title = 'Welcome!';

msgbox(msg_body, msg_title);
% --- END Welcome Message
